### ISSUE TITLE
di18n.config.js配置文件缺少文档提示

### ISSUE THREAD

**Issue by Orange8** [didi/di18n#1]
di18n.config.js配置文件缺少文档提示，希望能出一个使用文档。readme提到的Google翻译（可选），这个要如何配置呢？

**Comment by yshaojun** [comment]
> di18n.config.js配置文件缺少文档提示，希望能出一个使用文档。readme提到的Google翻译（可选），这个要如何配置呢？

可以参考 [文档](https://github.com/didi/di18n/tree/master/docs) 和 [代码](https://github.com/didi/di18n/blob/master/packages/di18n-cli/src/utils/reactOptions.js )，启用 Google 翻译，可以在配置文件的 `disableAutoTranslate` 改为 `false`。
