### ISSUE TITLE
npx di18n sync后，文本没有被正确翻译

### ISSUE THREAD

**Issue by CFsjp** [didi/di18n#11]
![image](https://user-images.githubusercontent.com/47934820/178438492-3caa4b35-4479-42f4-912a-c2bbfebcf1e5.png)
当运行npx di18n sync后，文本没有被正确翻译。期待翻译成对应语言

**Comment by yshaojun** [comment]
因 google 翻译国内被墙，默认关闭自动翻译，打开需再配置文件里改 disableAutoTranslate=false
https://github.com/didi/di18n/blob/master/packages/di18n-cli/src/utils/reactOptions.js#L17

**Comment by CFsjp** [comment]
disableAutoTranslate = false 后，这个di18n是如何翻译的呢？我卡在这里了
<img width="837" alt="image" src="https://user-images.githubusercontent.com/47934820/182306905-a1e1a185-3c27-4a31-a021-716a7a5cf1c8.png">

**Comment by jsm1003** [comment]
> disableAutoTranslate = false 后，这个di18n是如何翻译的呢？我卡在这里了 <img alt="image" width="837" src="https://user-images.githubusercontent.com/47934820/182306905-a1e1a185-3c27-4a31-a021-716a7a5cf1c8.png">

这个功能可能需要你自己的机器支持翻墙才可用
