### ISSUE TITLE
国际化中复数的处理

### ISSUE THREAD

**Issue by AyaneruQAQ** [didi/di18n#12]
比如 `${n}个苹果`，翻译的时候需要根据n来决定是apples还是apple,这种情况有什么好的解决办法吗

**Comment by jsm1003** [comment]
@AyaneruQAQ 这个确实没有好办法，di18n 只是语料替换，并不是翻译，这个你可以准备两份语料，一份是单数苹果，一份是复数，代码中通过变量 n 判断采用哪种语料
