### ISSUE TITLE
di18n-react依赖问题

### ISSUE THREAD

**Issue by AyaneruQAQ** [didi/di18n#14]
请问di18n-react是didi自己开发的库还是对其他国际化库进行了一层封装，我在github没有搜索到这个repo，希望能看下使用文档

**Comment by jsm1003** [comment]
@AyaneruQAQ di18n-react 是 didi 自己开发的库，就在这个 di18n 的文件目录下面https://github.com/didi/di18n/blob/master/packages/di18n-react/index.d.ts
