### ISSUE TITLE
prettier格式化配置跟项目本地不一致问题，是否可以检查项目本身有没有prettier配置有的话用项目的配置格式化

### ISSUE THREAD

**Issue by chenxia11** [didi/di18n#5]
![image](https://user-images.githubusercontent.com/22471374/94385371-9ce63280-0177-11eb-8cf4-256e0a588cc5.png)

**Comment by yshaojun** [comment]
可以将 prettier 配置到 di18n.config.js 里 https://github.com/didi/di18n/blob/master/examples/vue-di18n/di18n.config.js#L14
